### PR TITLE
Add cookie support

### PR DESCRIPTION
**Pull request by rogeriochaves**
The user just need to have write permissions for the cookie.txt file

### CODE REVIEW

**Comment by joshdick** [comment]
I've thought about using `CURLOPT_COOKIEJAR` before, but I don't believe this is a good solution for multiple simultaneous users since they will all be sharing the same set of cookies.

As it is, this code may not work as intended anyway -- you may need to use `CURLOPT_COOKIEFILE` in conjunction with `CURLOPT_COOKIEJAR` (COOKIEJAR is the write location, while COOKIEFILE is the read location) but I haven't tried this myself.

**Comment by rogeriochaves** [comment]
@joshdick yeah, I didn't thought about the multiple simultaneous users case, thanks for noticing

**Comment by lesander** [comment]
PHP Session-specific cookies?

**Comment by joshdick** [comment]
@lesander This is mostly a note for myself :) Even with session-specific cookies, special care would need to be taken to make sure proxied sites don't unintentionally receive each others' cookies, even when originating from a single user, since the users' browser would see each different site as originating from the same origin (the proxy).

**Comment by PeteLambert** [comment]
Hi there,

I'm hoping to use this to run a small personal service app through. The no-cookie thing is preventing my from logging into my site. 

Is the a fix / crack / patch etc for a single-user situation like mine? I don't work in php, but I work in python so I maybe be able to fuddle if you have ideas.

Thank you kindly,

**Comment by joshdick** [comment]
I just opened #69 for cookie support. It works in very basic testing but isn't production ready (yet); use it at your own risk!

**Pull request closed without merging**
