### PR TITLE
auth basic support

### PR DESCRIPTION
**Pull request by un-fmunozs**
Tested on httpbin and seems to be working
http://localhost/miniProxy.php/http://user:passwd@httpbin.org/basic-auth/user/passwd

### CODE REVIEW

**Comment by un-fmunozs** [comment]
Just wanted to add, I only supported auth basic because that's what I needed, maybe I should just update the PR with CURLAUTH_ANY ? that's an alias for CURLAUTH_BASIC | CURLAUTH_DIGEST | CURLAUTH_GSSNEGOTIATE | CURLAUTH_NTLM

**Comment by joshdick** [comment]
This pull request contains code with changes not relevant to basic auth, with some (commented) dead code, and with some changes that are redundant with existing miniProxy code. For example, I implemented proxifying <meta> tags with an 'http-equiv="refresh"' attribute in 5265fce5e608112d2c013815978b3fcb1e8d6547 without realizing that it was already implemented in this pull request.

Thanks very much for submitting the pull request, but I am not going to merge it in its current state. I would consider reopening and merging it if you clean it up. 😄

**Comment by un-fmunozs** [comment]
It's OK, I screwed it up not creating a branch for this PR and some weeks later did additional commits 😄  I had several issues while trying to proxy-fy an oracle administration console, needed to add cookies, force ssl, referrer support,  and even fix some links generated by javascript... I'll give it a try later again.

**Comment by joshdick** [comment]
For what it's worth, http://localhost/miniProxy.php?http://user:passwd@httpbin.org/basic-auth/user/passwd seems to work fine with the latest miniProxy code with no other changes.

I also just pushed 6c0c79f4d26b01c4a3b10a610259c5d3b5684d8e which removes the `CURLOPT_FAILONERROR` option, which allows browsers to interactively do basic authentication through miniProxy.

So, basic authentication appears to work, unless there's something I'm not understanding?

**Pull request closed without merging**
