### PR TITLE
Compatibilidade com PHP 5.3.3

### PR DESCRIPTION
**Pull request by silviogarbes**
Permitir a compatibilidade com o PHP 5.3.3

### CODE REVIEW

**Comment by joshdick** [comment]
Gracias! 👍

**Comment by joshdick** [comment]
Actually, 5.4.7 is still required (see #39).

From Google Translate / de Google Translate:

En realidad, 5.4.7 todavía es necesario (ver # 39).

**Comment by seogates55** [comment]
it's very Useful Mate....
But i have some cases 'bout Whitelist url's..
i don't understand 'bout corresponding Expression will we put to whitelisting the url's...
should we put the path url,or just domain name or should we put the gethostnamePattern at there?
i just wonder if you want to assist my cases...
very big Thanks Mate....
image

**Comment by joshdick** [comment]
@seogates55 `$whitelistPatterns` is an array of [regular expressions](https://en.wikipedia.org/wiki/Regular_expression). You can either write a regular expression manually, or generate one for a given domain name by passing that domain name to the `gethostnamePattern()` helper function.

If you have more questions, please open a new issue instead of tacking on to this existing/unrelated one.

**Pull request merged**
